config/routes.rb
Rails.application.routes.draw do
  get '/team' , to: 'statique#team'
  get '/contact' , to: 'statique#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/statique_controller.rb
class StatiqueController < ApplicationController
  def team
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statique_helper.rb
module StatiqueHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>


    <title>TheGossipProject</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <header>
    <div class ="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <i class="fas fa-user"></i>
        <%= link_to "Team", team_path %>
      </li>
      <li class="nav-item">
        <i class="fas fa-envelope"></i>
        <%= link_to "Contact", contact_path %>
      </li>
    </ul>
  </div>
  </nav>
</div>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/statique/contact.html.erb
<h1>Statique#contact</h1>
<p>Find me in app/views/statique/contact.html.erb</p>

app/views/statique/team.html.erb
<h1>Statique#team</h1>
<p>Find me in app/views/statique/team.html.erb</p>